Torneo.App/Torneo.App.Frontend/Pages/DTs/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.DTs
{
    public class CreateModel : PageModel
    {
        private readonly IRepositorioDT _repoDT;
        public DirectorTecnico dt { get; set; }
        public CreateModel(IRepositorioDT repoDT)
        {
            _repoDT = repoDT;
        }
        public void OnGet()
        {
            dt = new DirectorTecnico();
        }
        public IActionResult OnPost(DirectorTecnico dt)
        {
            _repoDT.AddDT(dt);
            return RedirectToPage("Index");
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/DTs/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.DTs
{
    public class DetailsModel : PageModel
    {
        private readonly IRepositorioDT _repoDT;

        public DirectorTecnico directorTecnico { get; set; }

        public DetailsModel(IRepositorioDT repoDT)
        {
            _repoDT = repoDT;
        }
        public IActionResult OnGet(int id)
        {
            directorTecnico = _repoDT.GetDT(id);
            if (directorTecnico == null)
            {
                return NotFound();
            }
            else
            {
                return Page();
            }
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/DTs/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Dts
{
    public class EditModel : PageModel
    {
        private readonly IRepositorioDT _repoDT;
        public DirectorTecnico DT { get; set; }
        public EditModel(IRepositorioDT repoDT)
        {
            _repoDT = repoDT;
        }

        //Invocar GetDT dentro del metodo OnGet tipo IActionResult
        public IActionResult OnGet(int id)
        {
            DT = _repoDT.GetDT(id);
            if (DT == null)
            {
                return NotFound();
            }
            else
            {
                return Page();
            }
        }
        public IActionResult OnPost(DirectorTecnico DT)
        {
            _repoDT.UpdateDT(DT);
            return RedirectToPage("Index");
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Equipos/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Persistencia;
using Torneo.App.Dominio;

namespace Torneo.App.Frontend.Pages.Equipos
{
    public class CreateModel : PageModel
    {
        private readonly IRepositorioEquipo _repoEquipo;
        private readonly IRepositorioMunicipio _repoMunicipio;
        private readonly IRepositorioDT _repoDT;

        public Equipo equipo { get; set; }
        public IEnumerable<Municipio> municipios { get; set; }
        public IEnumerable<DirectorTecnico> dts { get; set; }

        public CreateModel(IRepositorioEquipo repoEquipo, IRepositorioMunicipio repoMunicipio, IRepositorioDT repoDT)
        {
            _repoEquipo = repoEquipo;
            _repoMunicipio = repoMunicipio;
            _repoDT = repoDT;
        }


        public void OnGet()
        {
            equipo = new Equipo();
            municipios = _repoMunicipio.GetAllMunicipios();
            dts = _repoDT.GetAllDTs();
        }

        public IActionResult OnPost(Equipo equipo, int idMunicipio, int idDT)
        {
            _repoEquipo.AddEquipo(equipo, idMunicipio, idDT);
            return RedirectToPage("Index");
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Equipos/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Equipos
{
    public class DetailsModel : PageModel
    {
        private readonly IRepositorioEquipo _repoEquipo;
        public Equipo equipo { get; set; }
        public DetailsModel(IRepositorioEquipo repoEquipo)
        {
            _repoEquipo = repoEquipo;
        }
        public IActionResult OnGet(int id)
        {
            equipo = _repoEquipo.GetEquipo(id);
            if(equipo == null)
            {
                return NotFound();
            }
            else
            {
                return Page();
            }
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Equipos/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Equipos
{
    public class EditModel : PageModel
    {
        private readonly IRepositorioEquipo _repoEquipo;
        private readonly IRepositorioMunicipio _repoMunicipio;
        private readonly IRepositorioDT _repoDT;
        public Equipo equipo { get; set; }
        public SelectList MunicipioOptions { get; set; }
        public SelectList DTOptions { get; set; }
        public int MunicipioSelected { get; set; }
        public int DTSelected { get; set; }
        public EditModel(IRepositorioEquipo repoEquipo, IRepositorioMunicipio repoMunicipio, IRepositorioDT repoDT)
        {
            _repoEquipo = repoEquipo;
            _repoMunicipio = repoMunicipio;
            _repoDT = repoDT;
        }

        public IActionResult OnGet(int id)
        {
            equipo = _repoEquipo.GetEquipo(id);
            MunicipioOptions = new SelectList(_repoMunicipio.GetAllMunicipios(), "Id", "Nombre");
            MunicipioSelected = equipo.Municipio.Id;
            DTOptions = new SelectList(_repoDT.GetAllDTs(), "Id", "Nombre");
            DTSelected = equipo.DirectorTecnico.Id;
            if (equipo == null)
            {
                return NotFound();
            }
            else
            {
                return Page();
            }
        }

        public IActionResult OnPost(Equipo equipo, int idMunicipio, int idDT)
        {
            _repoEquipo.UpdateEquipo(equipo, idMunicipio, idDT);
            return RedirectToPage("Index");
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Equipos/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Persistencia;
using Torneo.App.Dominio;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Torneo.App.Frontend.Pages.Equipos
{
    public class IndexModel : PageModel
    {
        private readonly IRepositorioEquipo _repoEquipo;
        public IEnumerable<Equipo> equipos { get; set; }
        private readonly IRepositorioMunicipio _repoMunicipio;
        public SelectList MunicipioOptions { get; set; }
        public int MunicipioSelected { get; set; }
        public string BusquedaActual { get; set; }
        public IndexModel(IRepositorioEquipo repoEquipo, IRepositorioMunicipio repoMunicipio)
        {
            _repoEquipo = repoEquipo;
            _repoMunicipio = repoMunicipio;
        }
        public void OnGet()
        {
            MunicipioOptions = new SelectList(_repoMunicipio.GetAllMunicipios(), "Id", "Nombre");
            equipos = _repoEquipo.GetAllEquipos();
            MunicipioSelected = -1;
            BusquedaActual = "";
        }
        public void OnPostFiltro(int idMunicipio)
        {
            MunicipioOptions = new SelectList(_repoMunicipio.GetAllMunicipios(), "Id", "Nombre");
            if (idMunicipio != -1)
            {
                MunicipioSelected = idMunicipio;
                equipos = _repoEquipo.GetEquiposMunicipio(MunicipioSelected);
            }
            else
            {
                equipos = _repoEquipo.GetAllEquipos();
                MunicipioSelected = -1;
            }
        }
        public void OnPostBuscar(string nombre)
        {
            MunicipioOptions = new SelectList(_repoMunicipio.GetAllMunicipios(), "Id", "Nombre");
            MunicipioSelected = -1;
            if (string.IsNullOrEmpty(nombre))
            {
                BusquedaActual = "";
                equipos = _repoEquipo.GetAllEquipos();
            }
            else
            {
                BusquedaActual = nombre;
                equipos = _repoEquipo.SearchEquipos(nombre);
            }
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Jugadores/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Jugadores
{
    public class CreateModel : PageModel
    {
        private readonly IRepositorioJugador _repoJugador;
        private readonly IRepositorioEquipo _repoEquipo;
        private readonly IRepositorioPosicion _repoPosicion;

        public CreateModel(IRepositorioJugador repoJugador, IRepositorioEquipo repoEquipo, IRepositorioPosicion repoPosicion)
        {
            _repoJugador = repoJugador;
            _repoEquipo = repoEquipo;
            _repoPosicion = repoPosicion;
        }

        public Jugador jugador { get; set; }
        public IEnumerable<Equipo> equipos { get; set; }
        public IEnumerable<Posicion> posiciones { get; set; }

        public void OnGet()
        {
            jugador = new Jugador();
            equipos = _repoEquipo.GetAllEquipos();
            posiciones = _repoPosicion.GetAllPosiciones();
        }

        public IActionResult OnPost(Jugador jugador, int idEquipo, int idPosicion)
        {
            _repoJugador.AddJugador(jugador, idEquipo, idPosicion);
            return RedirectToPage("Index");
        }

    }
}

Torneo.App/Torneo.App.Frontend/Pages/Jugadores/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;


namespace Torneo.App.Frontend.Pages.Jugadores
{

    public class DetailsModel : PageModel
    {   
        //Atributo de IRepositorioJugador
        private readonly IRepositorioJugador _repoJugador;
        public Jugador jugador { get; set; }


        //Contrucctor
        public DetailsModel(IRepositorioJugador repoJugador)
        {
            _repoJugador = repoJugador;
        }

        //metodo OnGet para buscar jugadores por el id invocando el metodo GetJugador de RepositorioJugador
        public IActionResult OnGet(int id)
        {
            jugador = _repoJugador.GetJugador(id);
            if(jugador == null)
            {
                return NotFound();
            }
            else
            {
                return Page();
            }
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Jugadores/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Jugadores
{
    public class EditModel : PageModel
    {
        //Atributos
        private readonly IRepositorioJugador _repoJugador;
        private readonly IRepositorioEquipo _repoEquipo;
        private readonly IRepositorioPosicion _repoPosicion;

        //Propiedades tipo jugador y tipo SelectList para poblar los selects de equipos y posiciones
        public Jugador jugador { get; set; }
        public SelectList EquipoOptions { get; set; }
        public SelectList PosicionOptions { get; set; }

        //Equipo y posicion que tiene asignado el jugador para que aparescan como seleccionados en los selects
        public int EquipoSelected { get; set; }
        public int PosicionSelected { get; set; }
        

        //Instanciar en el constructor _repoEquipo, _repoMunicipio, _repoDT
        public EditModel(IRepositorioJugador repoJugador, IRepositorioEquipo repoEquipo, IRepositorioPosicion repoPosicion)
        {
            _repoJugador = repoJugador;
            _repoEquipo = repoEquipo;
            _repoPosicion = repoPosicion;
        }

        //Se inicializan las propiedades e instacian los SelectList.
        public IActionResult OnGet(int id)
        {
            jugador = _repoJugador.GetJugador(id);
            EquipoOptions = new SelectList(_repoEquipo.GetAllEquipos(), "Id", "Nombre");
            EquipoSelected = jugador.Equipo.Id;
            PosicionOptions = new SelectList(_repoPosicion.GetAllPosiciones(), "Id", "Nombre");
            PosicionSelected = jugador.Posicion.Id;

            //Validacion si el equipo es null retorne un No encontrado, de lo contrario carga el Page
            if (jugador == null)
            {
                return NotFound();
            }
            else
            {
                return Page();
            }
        }

        public IActionResult OnPost(Jugador jugador, int idEquipo, int idPosicion)
        {
            _repoJugador.UpdateJugador(jugador, idEquipo, idPosicion);
            return RedirectToPage("Index");
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Municipios/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Municipios
{
    public class CreateModel : PageModel
    {
        private readonly IRepositorioMunicipio _repoMunicipio;
        public Municipio municipio { get; set; }
        public CreateModel(IRepositorioMunicipio repoMunicipio)
        {
            _repoMunicipio = repoMunicipio;
        }
        public void OnGet()
        {
            municipio = new Municipio();
        }
        public IActionResult OnPost(Municipio municipio)
        {
            // if(ModelState.IsValid)
            // {
                _repoMunicipio.AddMunicipio(municipio);
                return RedirectToPage("Index");
            // }
            // else
            // {
            //     return Page();
            // }
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Municipios/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Municipios
{
    public class DetailsModel : PageModel
    {
        private readonly IRepositorioMunicipio _repoMunicipio;
        public Municipio municipio { get; set; }
        public DetailsModel(IRepositorioMunicipio repoMunicipio)
        {
            _repoMunicipio = repoMunicipio;
        }
        public IActionResult OnGet(int id)
        {
            municipio = _repoMunicipio.GetMunicipio(id);
            if (municipio == null)
            {
                return NotFound();
            }
            else
            {
                return Page();
            }
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Municipios/Edit.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Municipios
{
    public class EditModel : PageModel
    {
        private readonly IRepositorioMunicipio _repoMunicipio;
        public Municipio municipio { get; set; }
        public EditModel(IRepositorioMunicipio repoMunicipio)
        {
            _repoMunicipio = repoMunicipio;
        }
        public IActionResult OnGet(int id)
        {
            municipio = _repoMunicipio.GetMunicipio(id);
            if (municipio == null)
            {
                return NotFound();
            }
            else
            {
                return Page();
            }
        }
        public IActionResult OnPost(Municipio municipio)
        {
            _repoMunicipio.UpdateMunicipio(municipio);
            return RedirectToPage("Index");
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Partidos/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Partidos
{
    public class CreateModel : PageModel
    {
        private readonly IRepositorioPartido _repoPartido;
        private readonly IRepositorioEquipo _repoEquipo;

        public Partido partido { get; set; }
        public IEnumerable<Equipo> equipos { get; set; }

        public CreateModel(IRepositorioPartido repoPartido, IRepositorioEquipo repoEquipo)
        {
            _repoPartido = repoPartido;
            _repoEquipo = repoEquipo;
        }

        public void OnGet()
        {
            partido = new Partido();
            equipos = _repoEquipo.GetAllEquipos();
        }

        public IActionResult OnPost(Partido partido, int EquipoLocalId, int EquipoVisitanteId)
        {
            _repoPartido.AddPartido(partido, EquipoLocalId, EquipoVisitanteId);
            return RedirectToPage("Index");
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Partidos/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Torneo.App.Dominio;
using Torneo.App.Persistencia;

namespace Torneo.App.Frontend.Pages.Partidos
{
    public class DetailsModel : PageModel
    {
        private readonly IRepositorioPartido _repoPartido;
        public Partido partido {get; set;}
        public DetailsModel(IRepositorioPartido repoPartido)
        {
            _repoPartido = repoPartido;
        }
        public IActionResult OnGet(int id)
        {
            partido = _repoPartido.GetPartido(id);
            if(partido == null)
            {
                return NotFound();
            }
            else
            {
                return Page();
            }
        }
    }
}

Torneo.App/Torneo.App.Frontend/Pages/Equipos/Create.cshtml
@page
@model Torneo.App.Frontend.Pages.Equipos.CreateModel
@{
}
<h1>Nuevo equipo</h1>
<form method="post">
    <div class="form-group">
        <label asp-for="equipo.Nombre"></label>
        <input asp-for="equipo.Nombre" required maxlength="30" class="form-control">
    </div>
    <div class="form-group">
        <label for="idMunicipio">Municipio</label>
        <select id="idMunicipio" name="idMunicipio" class="form-control" required>
            @foreach (var municipio in Model.municipios)
            {
                <option value="@municipio.Id">@municipio.Nombre</option>
            }
        </select>
    </div>
    <div class="form-group">
    <div>
        <label for="idDT">D.T.</label>
        <select id="idDT" name="idDT" class="form-control" required>
            @foreach (var dt in Model.dts)
            {
                <option value="@dt.Id">@dt.Nombre</option>
            }
        </select>
    </div>
    <button type="submit" class="btn btn-primary btn-block">Crear equipo</button>
</form>
<a class="btn btn-secondary" asp-page="./Index">Volver</a>

Torneo.App/Torneo.App.Frontend/Pages/Equipos/Details.cshtml
@page
@model Torneo.App.Frontend.Pages.Equipos.DetailsModel
@{
}
<h1>Detalle del municipio</h1>
<table class="table table-dark table-striped">
    <tr>
        <th scope="col">Id</th>
        <td>@Model.equipo.Id</td>
    </tr>
    <tr>
        <th scope="col">Nombre</th>
        <td>@Model.equipo.Nombre</td>
    </tr>
    <tr>
        <th scope="col">Municipio</th>
        <td>@Model.equipo.Municipio.Nombre</td>
    </tr>
    <tr>
        <th scope="col">Director técnico</th>
        <td>@Model.equipo.DirectorTecnico.Nombre</td>
    </tr>
</table>
<a class="btn btn-primary" asp-page="./Index">Volver</a>

Torneo.App/Torneo.App.Frontend/Pages/Equipos/Edit.cshtml
@page
@model Torneo.App.Frontend.Pages.Equipos.EditModel
@{
}
<h1>Editar equipo</h1>
<form method="post">
    <div class="form-group">
        <label asp-for="equipo.Id"></label>
        <input asp-for="equipo.Id" class="form-control" readonly>
    </div>
    <div class="form-group">
        <label asp-for="equipo.Nombre"></label>
        <input asp-for="equipo.Nombre"  maxlength="30"  class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="MunicipioSelected"></label>
        <select asp-for="MunicipioSelected" asp-items="@Model.MunicipioOptions"name="idMunicipio" class="form-control"></select>
    </div>
    <div class="form-group">
        <label asp-for="DTSelected"></label>
        <select asp-for="DTSelected" asp-items="@Model.DTOptions"name="idDT" class="form-control"></select>
    </div>
    <button type="submit" class="btn btn-primary btn-block">Editar equipo</button>
</form>
<a class="btn btn-secondary" asp-page="./Index">Volver</a>

Torneo.App/Torneo.App.Frontend/Pages/Equipos/Index.cshtml
@page
@model Torneo.App.Frontend.Pages.Equipos.IndexModel
@{
}
<form method="post">
    <div class="input-group mb-3">
        <select asp-for="MunicipioSelected" asp-items="@Model.MunicipioOptions"
        name="idMunicipio" class="form-control">
        <option value="-1">Ver todos</option>
        </select>
        <button class="btn btn-outline-secondary" asp-page-handler="Filtro">
            Filtrar
        </button>
    </div>
</form>
<form method="post">
    <div class="input-group mb-3">
    <input asp-for="@Model.BusquedaActual" name="nombre" class="form-control">
    <button class="btn btn-outline-secondary" asp-page-handler="Buscar">
        Buscar
    </button>
    </div>
</form>
<h1>Listado de Equipos
<a class="btn btn-primary" asp-page="./Create">Crear equipos</a>
</h1>
<table class="table table-dark table-striped">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Id</th>
            <th scope="col">Nombre</th>
            <th scope="col">Municipio</th>
            <th scope="col">Director Técnico</th>
            <th scope="col">Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach(var equipo in Model.equipos)
        {
            <tr>
                <td>@equipo.Id</td>
                <td>@equipo.Nombre</td>
                <td>@equipo.Municipio.Nombre</td>
                <td>@equipo.DirectorTecnico.Nombre</td>
                <td>
                    <a class="btn btn-primary" asp-page="./Details" asp-route-id="@equipo.Id">
                        Detalle
                    </a>
                    <a class="btn btn-secondary" asp-page="./Edit" asp-route-id="@equipo.Id">
                        Editar
                    </a>
                </td>
            </tr>
        }
    </tbody>
</table>